# Site settings
author: Devin Belden
title: DS by DB
header-img: img/home-bg.png
email: devin.belden.28@gmail.com
copyright_name: Devin Belden
description: > # this means to ignore newlines until "baseurl:"
  Looking at the world through data
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  devinbelden

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
